import type { Metadata } from "next";
// import { Source_Sans_3, Inter_Tight, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";

// export const sourcesans = Source_Sans_3({
//   variable: "--font-source-sans-3",
//   subsets: ["latin"],
// });

// export const intertight = Inter_Tight({
//   variable: "--font-inter-tight",
//   subsets: ["latin"],
// });

// export const plusjakartasans = Plus_Jakarta_Sans({
//   variable: "--font-plus-jakarta-sans",
//   subsets: ["latin"],
// })

export const metadata: Metadata = {
  title: "Cloud and Digital Technology Services | Enpointe",
  description: "Generated by create next app",
  icons: {
    icon: "/Enpointe-Black-Favicon.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
